# -*- coding: utf-8 -*-
"""try.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hH_ymgBOHlXSDarrRWuehC0ZRfGmdMYl

#First code
"""

a = int(input("Enter a: "))
b = int(input("Enter b: "))
print(a+b)

year=int(input("Enter your birth year: "))
age= 2026 - year
print(age)

leng2th= int(input("Enter lenth: "))
breath =int(input("Enter breath: "))
print(length*breath)

# name= input("Enter your name: ")
# age= int(input("Enter your age: "))
# h= float(input("Enter your height: "))
# print(name, age, h)

# _try=1
# print(_try)

a= int(input("Enter first number:  "))
b= int(input("Enter second number:  "))
print("The sum is: ", a+b)
print("The subtract is: ", a-b)
print("The multiply is: ", a*b)
print("The division is: ", a/b)
print("The floored Division is: ", a//b)
print("The modulo is: ", a%b)
print("The power is: ", a**b)

print(6*2/3)

# Print("Hello World")

BirthYear= int(input("Enter the birth year: "))
age= 2026-BirthYear
print("The age is: ", age)

length= int(input("Enter the length: "))
breath= int(input("Enter the breath: "))
area= length* breath
print(area)

length= float(input("Enter the length: "))
breath= float(input("Enter the breath: "))
area= length* breath
print(area)

a= int(input("Enter a number: "))
print("The square is: ", a**2)

a= int(input("Enter a number: "))
b= int(input("Enter Other Number: "))
a **= b
print(a)

# Membership operator

"a" in "Add"

"F" in "Fusion"

"d"    not in "Devanshu"

print(20//3)

